### PR TITLE
rustpkg support

### PR DESCRIPTION
**Pull request by sbillig**
[Review on Reviewable](https://reviewable.io/reviews/servo/rust-http-client/5)

### CODE REVIEW

**Comment by metajack** [comment]
Just a note here that I plan to look at this soon now that the dependencies and servo are all compiling with 0.6 rust (or post 0.6 Rust really).

**Comment by jdm** [comment]
Pinging @metajack for followup :)

**Comment by metajack** [comment]
Sorry about the delay.

I just checked this out and `rustpkg build` seems to only show me the help. Is rustpkg in a bad state, or is this patch out of date, or am I just doing it wrong?

cc @catamorphism

**Comment by sbillig** [comment]
@metajack On a build from rust's incoming branch as of last night, `rustpkg build` shows the help message, but `rust pkg build` works. I haven't looked into this at all, but the behavior is the same for any package, not just this one.

(In rust 0.6 `rustpkg` and `rust pkg` both work)

**Comment by catamorphism** [comment]
I mentioned this to @metajack during the meeting, but just in case: at least for now, you need to write `rustpkg build pkgid`. I haven't looked at the `rust` tool so I'm not sure what that does.

**Comment by metajack** [comment]
When you say `rust pkg build` works, I suspect you are getting an older rustpkg running. Current rustpkg must be invoked with the pkgid, and rustpkg::build() no longer exists.

I'm going to leave this open to track progress, but this pull request is going to need some changes to work once rustpkg is farther along. I'll update here as progress is made.

**Comment by metajack** [comment]
I think it's safe to close this.

**Pull request closed without merging**
